name: Publish to PyPI

on:
  push:
    tags:
      - "v*"   # Only run on tags like v0.1.2

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine bump2version

    # 4. Build package
    - name: Build package
      run: python -m build

    # 5. List dist folder (debug)
    - name: List dist folder
      run: ls -la dist/

    # 6. Publish to PyPI
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
