name: Python Package CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements"
        pip install setuptools wheel twine pytest flake8 bump2version

    # 4. Lint code
    - name: Lint code
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    # 5. Run tests
    - name: Run tests
      run: pytest

    # 6. Determine version bump based on commit message
    - name: Determine version bump
      id: bump
      run: |
        LAST_COMMIT=$(git log -1 --pretty=%B)
        echo "Last commit message: $LAST_COMMIT"

        if echo "$LAST_COMMIT" | grep -q "BREAKING CHANGE"; then
          echo "type=major" >> $GITHUB_OUTPUT
        elif echo "$LAST_COMMIT" | grep -q "^feat"; then
          echo "type=minor" >> $GITHUB_OUTPUT
        else
          echo "type=patch" >> $GITHUB_OUTPUT
        fi

    # 7. Bump version
    - name: Bump version
      run: |
        bump2version ${{ steps.bump.outputs.type }} --allow-dirty --commit --tag

    # 8. Build package
    - name: Build package
      run: python setup.py sdist bdist_wheel

    # 9. Publish to PyPI
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python -m twine upload dist/*
